name: Lint
on: push
jobs:
  eslint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: yarn install --frozen-lockfile
      - run: yarn eslint
